#!/bin/sh

echo "${PWD##*/}: started."

set -x

URL=$(curl -s https://api.github.com/repos/Sifchain/sifchain-ui/releases/latest | jq -r '.assets[0].browser_download_url')
VER=$(curl -s https://api.github.com/repos/Sifchain/sifchain-ui/releases/latest | jq -r '.assets[0].name')

if ! $(grep -qw "^${VER}$" /root/current); then
  OLDVER=$(cat /root/previous)
  rm -f /tmp/archive.zip

  set -e
  wget -qO /tmp/archive.zip -- $URL
  rm -rf /usr/share/nginx/html
  mkdir /usr/share/nginx/html
  unzip /tmp/archive.zip
  mv app/dist/* /usr/share/nginx/html/
  set +e

  rm -rf app
  cat /root/current > /root/previous
  echo $VER > /root/current
fi

sleep 2h
