#!/bin/sh
# Collect all logs which come to /dev/log
exec 2>&1

echo "${PWD##*/}: started."

set -x
exec chpst -Unobody socklog unix /dev/log
# exec socklog unix /dev/log
# exec socat UNIX-LISTEN:/dev/log,reuseaddr,fork -
