---
version: "2.0"
services:
  razer-aikit-image-gen:
    image: razerofficial/aikit:cuda13.0-torch2.11.0-vllm0.20.0-aikit0.4.0
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 7860
        as: 7860
        to:
          - global: true
    command:
      - bash
      - "-lc"
    args:
      - |
        set -m
        export SHELL=`readlink -f /proc/$$$$/exe`
        rzr-aikit ui run &
        AIKIT_PID=$!
        trap 'wait $AIKIT_PID' SIGCHLD SIGTERM SIGINT
        jupyter lab \
          --ip="0.0.0.0" \
          --port=8888 \
          --no-browser \
          --IdentityProvider.token='' \
          --PasswordIdentityProvider.hashed_password="$(python -c "from jupyter_server.auth import passwd; print(passwd('RazerAI'))")"
profiles:
  compute:
    razer-aikit-image-gen:
      resources:
        cpu:
          units: 1
        memory:
          size: 4Gi
        storage:
          - size: 10Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        razer-aikit-image-gen:
          denom: uact
          amount: 100000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
deployment:
  razer-aikit-image-gen:
    dcloud:
      profile: razer-aikit-image-gen
      count: 1
